[package]
name = "oguard"
version = "0.0.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/jacobtread/oguard"
authors = ["Jacobtread <jacobtread@gmail.com>"]
readme = "README.md"
description = "OGuard"

[dependencies]
# Web framework
axum = "0.7"

# Environment variables
dotenvy = "0.15.7"

# Desktop notifications
notify-rust = "4.11.0"

# Logging
log = "0.4"
env_logger = "0.11"

# USB HID 
hidapi = "2.6.1"

# Serialization
serde = { version = "1", features = ["derive"] }
serde_json = "1"

# Error handling
thiserror = "1"
anyhow = "1"

# Async runtime & utilities
tokio = { version = "1", features = ["full"] }
tokio-stream = { version = "0.1", features = ["sync", "full"] }
futures = "0.3.30"
